# https://taskfile.dev

version: "3"

# Global variables
vars:
  MSG: "Default commit message"

# Default task
tasks:
  default:
    desc: Display all available tasks
    cmds:
      - task -a
    silent: true

  init:
    env:
      desc: Initialize base tools
      cmds:
        - uv run bootstrap.py init

  reqs:
    desc: "Install packages from requirements-dev file"
    cmds:
      - uv run bootstrap.py install-reqs --timeout 600

  reqs_from_file:
    desc: "Install packages from a specific file"
    cmds:
      - uv run bootstrap.py install-reqs --file requirements.txt

  reqs_verbose:
    desc: "Install packages with verbose output"
    cmds:
      - uv run bootstrap.py -vv install-reqs

  run-demo:
      desc: "Run the demonstration code"
      cmds:
        - uv run bootstrap.py demo

  run-main:
    desc: "Run main.py installed with uv init"
    cmds:
      - uv run main.py

  check:
    desc: "Run Omarchy diagnostic pipeline"
    cmds:
      - uv run omarchy_check.py --verbose
    silent: false

  arch_check:
    desc: "Run Arch Omarchy diagnostic pipeline"
    cmds:
      - uv run arch_check.py --verbose
    silent: false

  ruff-fmt:
    desc: "Format Python code using Ruff"
    cmds:
      - uv run ruff check . --select ALL --fix-only
      - uv run ruff format .
    sources:
      - '**/*.py'
    silent: false

  git:
    desc: "Add, commit, and push all changes"
    cmds:
      - git add .
      - git commit -m "{{.MSG}}"
      - git push
